### ISSUE TITLE
Please integrate it into netbeans

### ISSUE THREAD

**Issue by Chris2011** [nmaggioni/IntelliJ-2-NetBeans#1]
What we have now is, we have an option to Import an Eclipse Project, what we not have is an option to import a intelliJ project. You can do this from File -> Import Project -> Eclipse Project. So it would be nice, if you can do a plugin in Java for doing this and add the entry to the File -> import Project -> IntelliJ Project.

Cheers

Chris

**Comment by nmaggioni** [comment]
Thanks for the suggestion, I'll look into it!
I wrote this script to avoid the use of NetBeans completely since its UI does not render correctly on my 4K screen, but I suppose that a plugin would be useful for most people.

**Comment by nmaggioni** [comment]
I wrote this script to avoid the use of NetBeans completely - its UI does not render correctly on my HiDPI screen, so I can't use it - but I suppose that a plugin would be useful for most people. As soon as I'll get NetBeans working correctly (even if it'd be an upstream issue...) I'll look into porting this to a plugin!

**Comment by Chris2011** [comment]
If you need help implementing stuff into netbeans, I have experiences with creating netbeans plugins, so I can help you, if it's needed.
Thx.

**Comment by nmaggioni** [comment]
My problem is with the IDE indeed, every element in its UI is displayed at half the size than it should be; that makes it unusable...
If you feel like it, I'd be honored if you forked my repo and built a plugin based on it :)

**Comment by Chris2011** [comment]
Please create a bug here: https://netbeans.org/bugzilla/enter_bug.cgi maybe netbeans can't handle 4k displays? Don't know.

**Comment by Chris2011** [comment]
If I have time, I will fork it, maybe.

**Comment by Chris2011** [comment]
Hey, good News. Apache NetBeans 9.0 can handle HiDPI Very Well, because of JDK 9.
